import os
import subprocess
import sys

from mcmanager.utils import config as cfgmod
from mcmanager.utils import gdrive as gdrv

# import loaders
from mcmanager.loaders import vanilla, paper, purpur, fabric, forge, neoforge

LOADERS = {
    "1": ("Vanilla", vanilla.install),
    "2": ("Paper", paper.install),
    "3": ("Purpur", purpur.install),
    "4": ("Fabric", fabric.install),
    "5": ("Forge", forge.install),
    "6": ("NeoForge", neoforge.install),
}


def load_cfg():
    return cfgmod.load_config()


def save_cfg(cfg):
    cfgmod.save_config(cfg)


def expand(path: str) -> str:
    return os.path.expanduser(path)


from mcmanager.utils.java import JAVA17


def generate_run_sh(path: str, ram: str):
    script = (
        "#!/bin/bash\n"
        "cd \"$(dirname \"$0\")\"\n"
        f"\"{JAVA17}\" -Xms{ram} -Xmx{ram} -jar server.jar nogui\n"
    )
    dest = os.path.join(path, "run.sh")
    with open(dest, "w") as f:
        f.write(script)
    os.chmod(dest, 0o755)


def accept_eula(path: str):
    with open(os.path.join(path, "eula.txt"), "w") as f:
        f.write("eula=true\n")


def create_server_properties(path: str, port: str):
    props = f"""#Minecraft server properties
#Generated by Minecraft Server Manager
server-port={port}
motd=A Minecraft Server
difficulty=easy
max-players=20
online-mode=true
"""
    with open(os.path.join(path, "server.properties"), "w") as f:
        f.write(props)


def create_server(cfg):
    print("\nСоздание сервера")
    print("Выберите загрузчик:")
    for key, (name, _) in LOADERS.items():
        print(f"{key}) {name}")
    loader_choice = input("> ")
    if loader_choice not in LOADERS:
        print("Неверный выбор")
        return
    loader_name, loader_func = LOADERS[loader_choice]
    version = input("Версия Minecraft: ")
    name = input("Имя сервера: ")
    ram = input("RAM (например 2G): ")
    port = input("Порт сервера (25565): ").strip() or "25565"
    print("Где хранить сервер:")
    print("1) Локально")
    print("2) На Google Drive")
    storage = input("> ")
    if storage == "2":
        # ensure gdrive mounted
        mountpoint = expand(cfg.get("gdrive_mount"))
        if not gdrv.is_mounted(mountpoint):
            print("Google Drive не смонтирован. Попытка монтирования...")
            gdrv.mount(cfg.get("gdrive_remote"), mountpoint)
        server_path = gdrv.ensure_server_dir(name, cfg)
    else:
        server_path = expand(os.path.join(cfg.get("servers_path"), name))
        os.makedirs(server_path, exist_ok=True)
    print(f"Устанавливаем {loader_name} {version} в {server_path}")
    try:
        loader_func(version, server_path)
    except Exception as e:
        print(f"Ошибка установки: {e}")
        return
    # save loader type
    with open(os.path.join(server_path, "loader.txt"), "w") as f:
        f.write(loader_name)
    # save version
    with open(os.path.join(server_path, "version.txt"), "w") as f:
        f.write(version)
    generate_run_sh(server_path, ram)
    accept_eula(server_path)
    create_server_properties(server_path, port)
    print("Сервер создан.")


def list_servers(cfg):
    results = []
    base = expand(cfg.get("servers_path"))
    if os.path.isdir(base):
        results.extend([os.path.join(base, d) for d in os.listdir(base)])
    # also include gdrive if mounted
    mountpoint = expand(cfg.get("gdrive_mount"))
    gd_base = os.path.join(mountpoint, "mcservers")
    if os.path.isdir(gd_base):
        results.extend([os.path.join(gd_base, d) for d in os.listdir(gd_base)])
    return results


def select_server(cfg):
    print("\nДоступные сервера:")
    servers = list_servers(cfg)
    for i, path in enumerate(servers, start=1):
        print(f"{i}) {path}")
    if not servers:
        print("Серверов нет")
        return
    choice = input("> ")
    try:
        idx = int(choice) - 1
        chosen = servers[idx]
    except Exception:
        print("Неверный выбор")
        return
    ram = input("Сколько RAM выделить (например 2G): ")
    run_server(chosen, ram, cfg)


def run_server(path: str, ram: str, cfg):
    # read loader type
    loader_file = os.path.join(path, "loader.txt")
    if os.path.exists(loader_file):
        with open(loader_file, "r") as f:
            loader = f.read().strip()
    else:
        loader = "Vanilla"  # default
    # read version
    version_file = os.path.join(path, "version.txt")
    if os.path.exists(version_file):
        with open(version_file, "r") as f:
            mc_version = f.read().strip()
    else:
        mc_version = "1.20.1"  # default
    from mcmanager.utils.java import ensure_java
    java_path = ensure_java(mc_version)
    if loader in ["Forge", "NeoForge"]:
        # use @ args
        user_args = os.path.join(path, "user_jvm_args.txt")
        unix_args = None
        for root, dirs, files in os.walk(os.path.join(path, "libraries")):
            if "unix_args.txt" in files:
                unix_args = os.path.join(root, "unix_args.txt")
                break
        if not unix_args:
            print("unix_args.txt not found")
            return
        # modify user_jvm_args to set RAM
        with open(user_args, "r") as f:
            content = f.read()
        # replace or add -Xmx and -Xms
        lines = content.split('\n')
        new_lines = []
        for line in lines:
            if line.startswith('#') or not line.strip():
                new_lines.append(line)
            elif line.startswith('-Xmx') or line.startswith('-Xms'):
                continue  # remove old
        new_lines.append(f"-Xmx{ram}")
        new_lines.append(f"-Xms{ram}")
        with open(user_args, "w") as f:
            f.write('\n'.join(new_lines))
        cmd = [java_path, f"@{user_args}", f"@{unix_args}", "nogui"]
    else:
        # standard jar
        runjar = os.path.join(path, "server.jar")
        if not os.path.exists(runjar):
            print("server.jar не найден")
            return
        cmd = [
            java_path,
            f"-Xms{ram}",
            f"-Xmx{ram}",
            "-jar",
            "server.jar",
            "nogui",
        ]
    if cfg.get("use_playit"):
        # start playit in background
        playit_path = os.path.join(os.getcwd(), "playit")
        if os.path.exists(playit_path):
            subprocess.Popen([playit_path, "start"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print("playit.gg туннель запущен. Проверьте https://playit.gg для адреса.")
        else:
            print("playit не найден. Скачайте с https://playit.gg")
    subprocess.run(cmd, cwd=path)


def settings(cfg):
    print("\nНастройки:")
    print(f"1) Путь к серверам: {cfg.get('servers_path')}")
    print(f"2) GDrive mount: {cfg.get('gdrive_mount')}")
    print(f"3) GDrive remote: {cfg.get('gdrive_remote')}")
    print(f"4) Использовать playit.gg туннель: {'Да' if cfg.get('use_playit') else 'Нет'}")
    print("5) Назад")
    choice = input("> ")
    if choice == "1":
        cfg['servers_path'] = input("Новый путь: ")
    elif choice == "2":
        cfg['gdrive_mount'] = input("Новый путь монтирования: ")
    elif choice == "3":
        cfg['gdrive_remote'] = input("Новый удалённый: ")
    elif choice == "4":
        cfg['use_playit'] = not cfg.get('use_playit', False)
        print(f"playit.gg {'включен' if cfg['use_playit'] else 'выключен'}")
    save_cfg(cfg)


def gdrive_menu(cfg):
    print("\nGoogle Drive:")
    print("1) Проверить монтирован")
    print("2) Монтировать")
    print("3) Синхронизировать локальную папку с облаком")
    print("4) Назад")
    choice = input("> ")
    mountpoint = expand(cfg.get('gdrive_mount'))
    if choice == "1":
        print("mounted" if gdrv.is_mounted(mountpoint) else "not mounted")
    elif choice == "2":
        try:
            gdrv.mount(cfg.get('gdrive_remote'), mountpoint)
            print("Mounting... Please wait a few seconds and check again.")
        except Exception as e:
            print(f"Error mounting: {e}")
    elif choice == "3":
        try:
            local = input("Локальный путь: ")
            remote = input("Облачный (например gdrive:folder): ")
            gdrv.sync(local, remote)
            print("Sync completed.")
        except Exception as e:
            print(f"Error syncing: {e}")


def main():
    cfg = load_cfg()
    while True:
        print("\nГлавное меню")
        print("1) Создать сервер")
        print("2) Выбрать сервер")
        print("3) Настройки")
        print("4) Google Drive")
        print("5) Выход")
        choice = input("> ")
        if choice == "1":
            create_server(cfg)
        elif choice == "2":
            select_server(cfg)
        elif choice == "3":
            settings(cfg)
        elif choice == "4":
            gdrive_menu(cfg)
        elif choice == "5":
            print("Выход")
            break
        else:
            print("Неверный выбор")


if __name__ == "__main__":
    main()
