import os
import subprocess
import sys
import signal
import psutil

from mcmanager.utils import config as cfgmod
from mcmanager.utils import gdrive as gdrv

# import loaders
from mcmanager.loaders import vanilla, paper, purpur, fabric, forge, neoforge

LOADERS = {
    "1": ("Vanilla", vanilla.install),
    "2": ("Paper", paper.install),
    "3": ("Purpur", purpur.install),
    "4": ("Fabric", fabric.install),
    "5": ("Forge", forge.install),
    "6": ("NeoForge", neoforge.install),
}


def load_cfg():
    return cfgmod.load_config()


def save_cfg(cfg):
    cfgmod.save_config(cfg)


def expand(path: str) -> str:
    return os.path.expanduser(path)


from mcmanager.utils.java import JAVA17


def generate_run_sh(path: str, ram: str):
    script = (
        "#!/bin/bash\n"
        "cd \"$(dirname \"$0\")\"\n"
        f"\"{JAVA17}\" -Xms{ram} -Xmx{ram} -jar server.jar nogui\n"
    )
    dest = os.path.join(path, "run.sh")
    with open(dest, "w") as f:
        f.write(script)
    os.chmod(dest, 0o755)


def accept_eula(path: str):
    with open(os.path.join(path, "eula.txt"), "w") as f:
        f.write("eula=true\n")


def create_server_properties(path: str, port: str):
    props = f"""#Minecraft server properties
#Generated by Minecraft Server Manager
server-port={port}
motd=A Minecraft Server
difficulty=easy
max-players=20
online-mode=true
"""
    with open(os.path.join(path, "server.properties"), "w") as f:
        f.write(props)


def create_server(cfg):
    print("\nСоздание сервера")
    print("Выберите загрузчик:")
    for key, (name, _) in LOADERS.items():
        print(f"{key}) {name}")
    loader_choice = input("> ")
    if loader_choice not in LOADERS:
        print("Неверный выбор")
        return
    loader_name, loader_func = LOADERS[loader_choice]
    version = input("Версия Minecraft: ")
    name = input("Имя сервера: ")
    ram = input("RAM (например 2G): ")
    port = input("Порт сервера (25565): ").strip() or "25565"
    print("Где хранить сервер:")
    print("1) Локально")
    print("2) На Google Drive")
    storage = input("> ")
    if storage == "2":
        # ensure gdrive mounted
        mountpoint = expand(cfg.get("gdrive_mount"))
        if not gdrv.is_mounted(mountpoint):
            print("Google Drive не смонтирован. Попытка монтирования...")
            gdrv.mount(cfg.get("gdrive_remote"), mountpoint)
        server_path = gdrv.ensure_server_dir(name, cfg)
    else:
        server_path = expand(os.path.join(cfg.get("servers_path"), name))
        os.makedirs(server_path, exist_ok=True)
    print(f"Устанавливаем {loader_name} {version} в {server_path}")
    try:
        loader_func(version, server_path)
    except Exception as e:
        print(f"Ошибка установки: {e}")
        return
    # save loader type
    with open(os.path.join(server_path, "loader.txt"), "w") as f:
        f.write(loader_name)
    # save version
    with open(os.path.join(server_path, "version.txt"), "w") as f:
        f.write(version)
    generate_run_sh(server_path, ram)
    accept_eula(server_path)
    create_server_properties(server_path, port)
    print("Сервер создан.")


def list_servers(cfg):
    results = []
    base = expand(cfg.get("servers_path"))
    if os.path.isdir(base):
        results.extend([os.path.join(base, d) for d in os.listdir(base)])
    # also include gdrive if mounted
    mountpoint = expand(cfg.get("gdrive_mount"))
    gd_base = os.path.join(mountpoint, "mcservers")
    if os.path.isdir(gd_base):
        results.extend([os.path.join(gd_base, d) for d in os.listdir(gd_base)])
    return results


def select_server(cfg):
    print("\nДоступные сервера:")
    servers = list_servers(cfg)
    for i, path in enumerate(servers, start=1):
        print(f"{i}) {path}")
    if not servers:
        print("Серверов нет")
        return
    choice = input("> ")
    try:
        idx = int(choice) - 1
        chosen = servers[idx]
    except Exception:
        print("Неверный выбор")
        return
    ram = input("Сколько RAM выделить (например 2G): ")
    run_server(chosen, ram, cfg)


def get_playit_config(cfg, kind: str) -> dict:
    """Return configured playit settings for server or voice."""
    if kind == "server":
        enabled = cfg.get("use_playit_server", cfg.get("use_playit", False))
    else:
        enabled = cfg.get("use_playit_voice", False)
    return {
        "enabled": enabled,
        "tunnel_type": cfg.get(f"playit_{kind}_tunnel_type", "playit"),
        "secret": cfg.get(f"playit_{kind}_secret", ""),
        "secret_path": cfg.get(f"playit_{kind}_secret_path", f"~/.mcmanager/playit_{kind}_secret.txt"),
        "log_path": cfg.get(f"playit_{kind}_log_path", f"~/.mcmanager/playit_{kind}.log"),
        "bin_path": cfg.get(f"playit_{kind}_bin_path", "./playit"),
        "stop_on_server_stop": cfg.get(f"playit_{kind}_stop_on_server_stop", True),
    }


def is_playit_running(kind: str, cfg) -> bool:
    """Check whether the requested playit tunnel is already running."""
    playit_cfg = get_playit_config(cfg, kind)
    log_path = os.path.expanduser(playit_cfg["log_path"])
    secret_path = os.path.expanduser(playit_cfg["secret_path"])
    try:
        for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
            try:
                cmdline = proc.info['cmdline']
                if not cmdline or 'playit' not in ' '.join(cmdline) or 'start' not in ' '.join(cmdline):
                    continue
                if log_path and log_path in ' '.join(cmdline):
                    return True
                if secret_path and secret_path in ' '.join(cmdline):
                    return True
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass
    except Exception:
        pass
    return False


def start_playit_tunnel(cfg, kind: str):
    """Start a specific playit tunnel: server or voice."""
    playit_cfg = get_playit_config(cfg, kind)
    if not playit_cfg["enabled"]:
        return None
    if playit_cfg["tunnel_type"] != "playit":
        print(f"Тип туннеля {playit_cfg['tunnel_type']} пока не поддерживается для {kind}")
        return None
    if is_playit_running(kind, cfg):
        print(f"playit.gg туннель для {kind} уже запущен")
        return None

    playit_path = os.path.expanduser(playit_cfg["bin_path"])
    if not os.path.isabs(playit_path):
        playit_path = os.path.join(os.getcwd(), playit_path)
    if not os.path.exists(playit_path):
        print(f"playit binary для {kind} не найден по пути: {playit_path}")
        return None

    cmd = [playit_path, "start"]
    secret = str(playit_cfg["secret"]).strip()
    secret_path = os.path.expanduser(playit_cfg["secret_path"])
    log_path = os.path.expanduser(playit_cfg["log_path"])
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    if secret_path:
        os.makedirs(os.path.dirname(secret_path), exist_ok=True)
        if secret:
            with open(secret_path, "w") as f:
                f.write(secret)
        cmd.extend(["--secret_path", secret_path])
    elif secret:
        cmd.extend(["--secret", secret])
    cmd.extend(["--log_path", log_path])

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
        print(f"playit.gg туннель для {kind} запущен (PID: {process.pid})")
        print(f"Логи: {log_path}")
        print("Проверьте https://playit.gg для адреса")
        return process
    except Exception as e:
        print(f"Ошибка запуска playit для {kind}: {e}")
        return None


def stop_playit_tunnel(cfg, kind: str):
    """Stop a specific playit tunnel process based on its configuration."""
    playit_cfg = get_playit_config(cfg, kind)
    if playit_cfg["tunnel_type"] != "playit":
        return
    log_path = os.path.expanduser(playit_cfg["log_path"])
    secret_path = os.path.expanduser(playit_cfg["secret_path"])
    try:
        for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
            try:
                cmdline = proc.info['cmdline']
                if not cmdline or 'playit' not in ' '.join(cmdline) or 'start' not in ' '.join(cmdline):
                    continue
                if log_path and log_path in ' '.join(cmdline) or secret_path and secret_path in ' '.join(cmdline):
                    proc.terminate()
                    try:
                        proc.wait(timeout=5)
                    except psutil.TimeoutExpired:
                        proc.kill()
                    print(f"playit.gg туннель для {kind} остановлен (был PID: {proc.pid})")
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass
    except Exception as e:
        print(f"Ошибка при остановке playit для {kind}: {e}")


def stop_all_playit_tunnels(cfg):
    stop_playit_tunnel(cfg, 'server')
    stop_playit_tunnel(cfg, 'voice')


def run_server(path: str, ram: str, cfg):
    # read loader type
    loader_file = os.path.join(path, "loader.txt")
    if os.path.exists(loader_file):
        with open(loader_file, "r") as f:
            loader = f.read().strip()
    else:
        loader = "Vanilla"  # default
    # read version
    version_file = os.path.join(path, "version.txt")
    if os.path.exists(version_file):
        with open(version_file, "r") as f:
            mc_version = f.read().strip()
    else:
        mc_version = "1.20.1"  # default
    from mcmanager.utils.java import ensure_java
    java_path = ensure_java(mc_version)
    if loader in ["Forge", "NeoForge"]:
        # use @ args
        user_args = os.path.join(path, "user_jvm_args.txt")
        unix_args = None
        for root, dirs, files in os.walk(os.path.join(path, "libraries")):
            if "unix_args.txt" in files:
                unix_args = os.path.join(root, "unix_args.txt")
                break
        if not unix_args:
            print("unix_args.txt not found")
            return
        # modify user_jvm_args to set RAM
        with open(user_args, "r") as f:
            content = f.read()
        # replace or add -Xmx and -Xms
        lines = content.split('\n')
        new_lines = []
        for line in lines:
            if line.startswith('#') or not line.strip():
                new_lines.append(line)
            elif line.startswith('-Xmx') or line.startswith('-Xms'):
                continue  # remove old
        new_lines.append(f"-Xmx{ram}")
        new_lines.append(f"-Xms{ram}")
        with open(user_args, "w") as f:
            f.write('\n'.join(new_lines))
        cmd = [java_path, f"@{user_args}", f"@{unix_args}", "nogui"]
    else:
        # standard jar
        runjar = os.path.join(path, "server.jar")
        if not os.path.exists(runjar):
            print("server.jar не найден")
            return
        cmd = [
            java_path,
            f"-Xms{ram}",
            f"-Xmx{ram}",
            "-jar",
            "server.jar",
            "nogui",
        ]
    server_config = get_playit_config(cfg, 'server')
    voice_enabled = cfg.get('voicechat_enabled', False)
    voice_config = get_playit_config(cfg, 'voice')
    if server_config['enabled']:
        start_playit_tunnel(cfg, 'server')
    if voice_enabled and voice_config['enabled']:
        start_playit_tunnel(cfg, 'voice')

    try:
        subprocess.run(cmd, cwd=path)
    except KeyboardInterrupt:
        print("\nСервер остановлен")
    finally:
        if server_config['enabled'] and server_config['stop_on_server_stop']:
            stop_playit_tunnel(cfg, 'server')
        if voice_enabled and voice_config['enabled'] and voice_config['stop_on_server_stop']:
            stop_playit_tunnel(cfg, 'voice')


def settings(cfg):
    print("\nНастройки:")
    print(f"1) Путь к серверам: {cfg.get('servers_path')}")
    print(f"2) GDrive mount: {cfg.get('gdrive_mount')}")
    print(f"3) GDrive remote: {cfg.get('gdrive_remote')}")
    print(f"4) Использовать playit.gg для сервера: {'Да' if cfg.get('use_playit_server', cfg.get('use_playit', False)) else 'Нет'}")
    print(f"5) VoiceChat включён: {'Да' if cfg.get('voicechat_enabled', False) else 'Нет'}")
    print(f"6) Использовать playit.gg для VoiceChat: {'Да' if cfg.get('use_playit_voice', False) else 'Нет'}")
    print("7) Настройки playit.gg для сервера")
    print("8) Настройки playit.gg для VoiceChat")
    print("9) Назад")
    choice = input("> ")
    if choice == "1":
        cfg['servers_path'] = input("Новый путь: ")
    elif choice == "2":
        cfg['gdrive_mount'] = input("Новый путь монтирования: ")
    elif choice == "3":
        cfg['gdrive_remote'] = input("Новый удалённый: ")
    elif choice == "4":
        cfg['use_playit_server'] = not cfg.get('use_playit_server', cfg.get('use_playit', False))
        print(f"playit.gg для сервера {'включен' if cfg['use_playit_server'] else 'выключен'}")
    elif choice == "5":
        cfg['voicechat_enabled'] = not cfg.get('voicechat_enabled', False)
        print(f"VoiceChat {'включен' if cfg['voicechat_enabled'] else 'выключен'}")
    elif choice == "6":
        cfg['use_playit_voice'] = not cfg.get('use_playit_voice', False)
        print(f"playit.gg для VoiceChat {'включен' if cfg['use_playit_voice'] else 'выключен'}")
    elif choice == "7":
        playit_settings(cfg, 'server')
    elif choice == "8":
        playit_settings(cfg, 'voice')
    save_cfg(cfg)


def playit_settings(cfg, kind: str):
    """Submenu for playit.gg configuration for server or voice."""
    kind_name = "сервера" if kind == 'server' else 'VoiceChat'
    while True:
        print(f"\nНастройки playit.gg для {kind_name}:")
        secret = cfg.get(f'playit_{kind}_secret', '')
        secret_display = f"{'*' * len(secret)}" if secret else "(не задан)"
        print(f"1) Secret key: {secret_display}")
        print(f"2) Secret path: {cfg.get(f'playit_{kind}_secret_path', f'~/.mcmanager/playit_{kind}_secret.txt')}")
        print(f"3) Log path: {cfg.get(f'playit_{kind}_log_path', f'~/.mcmanager/playit_{kind}.log')}")
        print(f"4) Playit binary path: {cfg.get(f'playit_{kind}_bin_path', './playit')}")
        print(f"5) Tunnel type: {cfg.get(f'playit_{kind}_tunnel_type', 'playit')}")
        print(f"6) Останавливать playit при остановке сервера: {'Да' if cfg.get(f'playit_{kind}_stop_on_server_stop', True) else 'Нет'}")
        print("7) Назад")
        choice = input("> ")
        if choice == "1":
            new_secret = input("Введите secret key (или оставьте пусто): ").strip()
            cfg[f'playit_{kind}_secret'] = new_secret
            if new_secret:
                print("Secret key сохранён")
            else:
                print("Secret key очищен")
        elif choice == "2":
            new_path = input("Новый путь для secret файла: ").strip()
            if new_path:
                cfg[f'playit_{kind}_secret_path'] = new_path
                print(f"Secret path: {new_path}")
        elif choice == "3":
            new_path = input("Новый путь для логов: ").strip()
            if new_path:
                cfg[f'playit_{kind}_log_path'] = new_path
                print(f"Log path: {new_path}")
        elif choice == "4":
            new_path = input("Путь к playit бинарнику: ").strip() or './playit'
            cfg[f'playit_{kind}_bin_path'] = new_path
            print(f"Playit binary path: {new_path}")
        elif choice == "5":
            new_type = input("Тип туннеля (playit): ").strip() or 'playit'
            cfg[f'playit_{kind}_tunnel_type'] = new_type
            print(f"Tunnel type: {new_type}")
        elif choice == "6":
            cfg[f'playit_{kind}_stop_on_server_stop'] = not cfg.get(f'playit_{kind}_stop_on_server_stop', True)
            print(f"Остановка при остановке сервера: {'включена' if cfg[f'playit_{kind}_stop_on_server_stop'] else 'отключена'}")
        elif choice == "7":
            break
        else:
            print("Неверный выбор")
    save_cfg(cfg)



def gdrive_menu(cfg):
    print("\nGoogle Drive:")
    print("1) Проверить монтирован")
    print("2) Монтировать")
    print("3) Синхронизировать локальную папку с облаком")
    print("4) Назад")
    choice = input("> ")
    mountpoint = expand(cfg.get('gdrive_mount'))
    if choice == "1":
        print("mounted" if gdrv.is_mounted(mountpoint) else "not mounted")
    elif choice == "2":
        try:
            gdrv.mount(cfg.get('gdrive_remote'), mountpoint)
            print("Mounting... Please wait a few seconds and check again.")
        except Exception as e:
            print(f"Error mounting: {e}")
    elif choice == "3":
        try:
            local = input("Локальный путь: ")
            remote = input("Облачный (например gdrive:folder): ")
            gdrv.sync(local, remote)
            print("Sync completed.")
        except Exception as e:
            print(f"Error syncing: {e}")


def main():
    cfg = load_cfg()
    while True:
        print("\nГлавное меню")
        print("1) Создать сервер")
        print("2) Выбрать сервер")
        print("3) Настройки")
        print("4) Google Drive")
        print("5) Выход")
        choice = input("> ")
        if choice == "1":
            create_server(cfg)
        elif choice == "2":
            select_server(cfg)
        elif choice == "3":
            settings(cfg)
        elif choice == "4":
            gdrive_menu(cfg)
        elif choice == "5":
            print("Выход")
            break
        else:
            print("Неверный выбор")


if __name__ == "__main__":
    main()
