import os
import subprocess
import sys
import signal
import psutil
import time
import threading

from mcmanager.utils import config as cfgmod
from mcmanager.utils import gdrive as gdrv

# import loaders
from mcmanager.loaders import vanilla, paper, purpur, fabric, forge, neoforge

LOADERS = {
    "1": ("Vanilla", vanilla.install),
    "2": ("Paper", paper.install),
    "3": ("Purpur", purpur.install),
    "4": ("Fabric", fabric.install),
    "5": ("Forge", forge.install),
    "6": ("NeoForge", neoforge.install),
}


def load_cfg():
    return cfgmod.load_config()


def save_cfg(cfg):
    cfgmod.save_config(cfg)


def expand(path: str) -> str:
    return os.path.expanduser(path)


from mcmanager.utils.java import JAVA17


def generate_run_sh(path: str, ram: str):
    script = (
        "#!/bin/bash\n"
        "cd \"$(dirname \"$0\")\"\n"
        f"\"{JAVA17}\" -Xms{ram} -Xmx{ram} -jar server.jar nogui\n"
    )
    dest = os.path.join(path, "run.sh")
    with open(dest, "w") as f:
        f.write(script)
    os.chmod(dest, 0o755)


def accept_eula(path: str):
    with open(os.path.join(path, "eula.txt"), "w") as f:
        f.write("eula=true\n")


def create_server_properties(path: str, port: str):
    props = f"""#Minecraft server properties
#Generated by Minecraft Server Manager
server-port={port}
motd=A Minecraft Server
difficulty=easy
max-players=20
online-mode=true
"""
    with open(os.path.join(path, "server.properties"), "w") as f:
        f.write(props)


def create_server(cfg):
    print("\nСоздание сервера")
    print("Выберите загрузчик:")
    for key, (name, _) in LOADERS.items():
        print(f"{key}) {name}")
    loader_choice = input("> ")
    if loader_choice not in LOADERS:
        print("Неверный выбор")
        return
    loader_name, loader_func = LOADERS[loader_choice]
    version = input("Версия Minecraft: ")
    name = input("Имя сервера: ")
    ram = input("RAM (например 2G): ")
    port = input("Порт сервера (25565): ").strip() or "25565"
    print("Где хранить сервер:")
    print("1) Локально")
    print("2) На Google Drive")
    storage = input("> ")
    if storage == "2":
        # ensure gdrive mounted
        mountpoint = expand(cfg.get("gdrive_mount"))
        if not gdrv.is_mounted(mountpoint):
            print("Google Drive не смонтирован. Попытка монтирования...")
            gdrv.mount(cfg.get("gdrive_remote"), mountpoint)
        server_path = gdrv.ensure_server_dir(name, cfg)
    else:
        server_path = expand(os.path.join(cfg.get("servers_path"), name))
        os.makedirs(server_path, exist_ok=True)
    print(f"Устанавливаем {loader_name} {version} в {server_path}")
    try:
        loader_func(version, server_path)
    except Exception as e:
        print(f"Ошибка установки: {e}")
        return
    # save loader type
    with open(os.path.join(server_path, "loader.txt"), "w") as f:
        f.write(loader_name)
    # save version
    with open(os.path.join(server_path, "version.txt"), "w") as f:
        f.write(version)
    generate_run_sh(server_path, ram)
    accept_eula(server_path)
    create_server_properties(server_path, port)
    print("Сервер создан.")


def list_servers(cfg):
    results = []
    base = expand(cfg.get("servers_path"))
    if os.path.isdir(base):
        results.extend([os.path.join(base, d) for d in os.listdir(base)])
    # also include gdrive if mounted
    mountpoint = expand(cfg.get("gdrive_mount"))
    gd_base = os.path.join(mountpoint, "mcservers")
    if os.path.isdir(gd_base):
        results.extend([os.path.join(gd_base, d) for d in os.listdir(gd_base)])
    return results


def select_server(cfg):
    print("\nДоступные сервера:")
    servers = list_servers(cfg)
    for i, path in enumerate(servers, start=1):
        print(f"{i}) {path}")
    if not servers:
        print("Серверов нет")
        return
    choice = input("> ")
    try:
        idx = int(choice) - 1
        chosen = servers[idx]
    except Exception:
        print("Неверный выбор")
        return
    ram = input("Сколько RAM выделить (например 2G): ")
    # Save last server and RAM
    cfg['last_server_path'] = chosen
    cfg['last_server_ram'] = ram
    save_cfg(cfg)
    run_server(chosen, ram, cfg)


def get_playit_config(cfg) -> dict:
    """Return configured playit settings."""
    return {
        "enabled": cfg.get("use_playit", False),
        "tunnel_type": cfg.get("playit_tunnel_type", "playit"),
        "secret": cfg.get("playit_secret", ""),
        "secret_path": cfg.get("playit_secret_path", "~/.mcmanager/playit_secret.txt"),
        "log_path": cfg.get("playit_log_path", "~/.mcmanager/playit.log"),
        "stop_on_server_stop": cfg.get("playit_stop_on_server_stop", True),
    }


def is_playit_running(cfg) -> bool:
    """Check whether playit tunnel is already running."""
    playit_cfg = get_playit_config(cfg)
    log_path = os.path.expanduser(playit_cfg["log_path"])
    secret_path = os.path.expanduser(playit_cfg["secret_path"])
    try:
        for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
            try:
                cmdline = proc.info['cmdline']
                if not cmdline or 'playit' not in ' '.join(cmdline) or 'start' not in ' '.join(cmdline):
                    continue
                if log_path and log_path in ' '.join(cmdline):
                    return True
                if secret_path and secret_path in ' '.join(cmdline):
                    return True
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass
    except Exception:
        pass
    return False


def start_playit_tunnel(cfg):
    """Start playit tunnel."""
    playit_cfg = get_playit_config(cfg)
    if not playit_cfg["enabled"]:
        return None
    if playit_cfg["tunnel_type"] != "playit":
        print(f"Тип туннеля {playit_cfg['tunnel_type']} пока не поддерживается")
        return None
    if is_playit_running(cfg):
        print("playit.gg туннель уже запущен")
        return None

    playit_path = os.path.join(os.getcwd(), "playit")
    if not os.path.exists(playit_path):
        print("playit не найден. Скачайте с https://playit.gg")
        return None

    cmd = [playit_path, "start"]
    secret = str(playit_cfg["secret"]).strip()
    secret_path = os.path.expanduser(playit_cfg["secret_path"])
    log_path = os.path.expanduser(playit_cfg["log_path"])
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    if secret_path:
        os.makedirs(os.path.dirname(secret_path), exist_ok=True)
        if secret:
            with open(secret_path, "w") as f:
                f.write(secret)
        cmd.extend(["--secret_path", secret_path])
    elif secret:
        cmd.extend(["--secret", secret])
    cmd.extend(["--log_path", log_path])

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
        print(f"playit.gg туннель запущен (PID: {process.pid})")
        print(f"Логи: {log_path}")
        print("Проверьте https://playit.gg для адреса")
        return process
    except Exception as e:
        print(f"Ошибка запуска playit: {e}")
        return None


def stop_playit_tunnel(cfg):
    """Stop playit tunnel process."""
    playit_cfg = get_playit_config(cfg)
    if playit_cfg["tunnel_type"] != "playit":
        return
    log_path = os.path.expanduser(playit_cfg["log_path"])
    secret_path = os.path.expanduser(playit_cfg["secret_path"])
    try:
        for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
            try:
                cmdline = proc.info['cmdline']
                if not cmdline or 'playit' not in ' '.join(cmdline) or 'start' not in ' '.join(cmdline):
                    continue
                if log_path and log_path in ' '.join(cmdline) or secret_path and secret_path in ' '.join(cmdline):
                    proc.terminate()
                    try:
                        proc.wait(timeout=5)
                    except psutil.TimeoutExpired:
                        proc.kill()
                    print(f"playit.gg туннель остановлен (был PID: {proc.pid})")
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass
    except Exception as e:
        print(f"Ошибка при остановке playit: {e}")



def run_server(path: str, ram: str, cfg):
    # read loader type
    loader_file = os.path.join(path, "loader.txt")
    if os.path.exists(loader_file):
        with open(loader_file, "r") as f:
            loader = f.read().strip()
    else:
        loader = "Vanilla"  # default
    # read version
    version_file = os.path.join(path, "version.txt")
    if os.path.exists(version_file):
        with open(version_file, "r") as f:
            mc_version = f.read().strip()
    else:
        mc_version = "1.20.1"  # default
    from mcmanager.utils.java import ensure_java
    java_path = ensure_java(mc_version)
    if loader in ["Forge", "NeoForge"]:
        # use @ args
        user_args = os.path.join(path, "user_jvm_args.txt")
        unix_args = None
        for root, dirs, files in os.walk(os.path.join(path, "libraries")):
            if "unix_args.txt" in files:
                unix_args = os.path.join(root, "unix_args.txt")
                break
        if not unix_args:
            print("unix_args.txt not found")
            return
        # modify user_jvm_args to set RAM
        with open(user_args, "r") as f:
            content = f.read()
        # replace or add -Xmx and -Xms
        lines = content.split('\n')
        new_lines = []
        for line in lines:
            if line.startswith('#') or not line.strip():
                new_lines.append(line)
            elif line.startswith('-Xmx') or line.startswith('-Xms'):
                continue  # remove old
        new_lines.append(f"-Xmx{ram}")
        new_lines.append(f"-Xms{ram}")
        with open(user_args, "w") as f:
            f.write('\n'.join(new_lines))
        cmd = [java_path, f"@{user_args}", f"@{unix_args}", "nogui"]
    else:
        # standard jar
        runjar = os.path.join(path, "server.jar")
        if not os.path.exists(runjar):
            print("server.jar не найден")
            return
        cmd = [
            java_path,
            f"-Xms{ram}",
            f"-Xmx{ram}",
            "-jar",
            "server.jar",
            "nogui",
        ]
    server_config = get_playit_config(cfg)
    if server_config['enabled']:
        start_playit_tunnel(cfg)

    try:
        subprocess.run(cmd, cwd=path)
    except KeyboardInterrupt:
        print("\nСервер остановлен")
    finally:
        if server_config['enabled'] and server_config['stop_on_server_stop']:
            stop_playit_tunnel(cfg)


def settings(cfg):
    print("\nНастройки:")
    print(f"1) Путь к серверам: {cfg.get('servers_path')}")
    print(f"2) GDrive mount: {cfg.get('gdrive_mount')}")
    print(f"3) GDrive remote: {cfg.get('gdrive_remote')}")
    print(f"4) Использовать playit.gg: {'Да' if cfg.get('use_playit', False) else 'Нет'}")
    print(f"5) Автозагрузка последнего сервера: {'Да' if cfg.get('auto_start_enabled', False) else 'Нет'}")
    print("6) Настройки playit.gg")
    print("7) Назад")
    choice = input("> ")
    if choice == "1":
        cfg['servers_path'] = input("Новый путь: ")
    elif choice == "2":
        cfg['gdrive_mount'] = input("Новый путь монтирования: ")
    elif choice == "3":
        cfg['gdrive_remote'] = input("Новый удалённый: ")
    elif choice == "4":
        cfg['use_playit'] = not cfg.get('use_playit', False)
        print(f"playit.gg {'включен' if cfg['use_playit'] else 'выключен'}")
    elif choice == "5":
        cfg['auto_start_enabled'] = not cfg.get('auto_start_enabled', False)
        print(f"Автозагрузка {'включена' if cfg['auto_start_enabled'] else 'выключена'}")
    elif choice == "6":
        playit_settings(cfg)
    save_cfg(cfg)


def playit_settings(cfg):
    """Submenu for playit.gg configuration."""
    while True:
        print("\nНастройки playit.gg:")
        secret = cfg.get('playit_secret', '')
        secret_display = f"{'*' * len(secret)}" if secret else "(не задан)"
        print(f"1) Secret key: {secret_display}")
        print(f"2) Secret path: {cfg.get('playit_secret_path', '~/.mcmanager/playit_secret.txt')}")
        print(f"3) Log path: {cfg.get('playit_log_path', '~/.mcmanager/playit.log')}")
        print(f"4) Tunnel type: {cfg.get('playit_tunnel_type', 'playit')}")
        print(f"5) Останавливать playit при остановке сервера: {'Да' if cfg.get('playit_stop_on_server_stop', True) else 'Нет'}")
        print("6) Назад")
        choice = input("> ")
        if choice == "1":
            new_secret = input("Введите secret key (или оставьте пусто): ").strip()
            cfg['playit_secret'] = new_secret
            if new_secret:
                print("Secret key сохранён")
            else:
                print("Secret key очищен")
        elif choice == "2":
            new_path = input("Новый путь для secret файла: ").strip()
            if new_path:
                cfg['playit_secret_path'] = new_path
                print(f"Secret path: {new_path}")
        elif choice == "3":
            new_path = input("Новый путь для логов: ").strip()
            if new_path:
                cfg['playit_log_path'] = new_path
                print(f"Log path: {new_path}")
        elif choice == "4":
            new_type = input("Тип туннеля (playit): ").strip() or 'playit'
            cfg['playit_tunnel_type'] = new_type
            print(f"Tunnel type: {new_type}")
        elif choice == "5":
            cfg['playit_stop_on_server_stop'] = not cfg.get('playit_stop_on_server_stop', True)
            print(f"Остановка при остановке сервера: {'включена' if cfg['playit_stop_on_server_stop'] else 'отключена'}")
        elif choice == "6":
            break
        else:
            print("Неверный выбор")
    save_cfg(cfg)



def gdrive_menu(cfg):
    print("\nGoogle Drive:")
    print("1) Проверить монтирован")
    print("2) Монтировать")
    print("3) Синхронизировать локальную папку с облаком")
    print("4) Назад")
    choice = input("> ")
    mountpoint = expand(cfg.get('gdrive_mount'))
    if choice == "1":
        print("mounted" if gdrv.is_mounted(mountpoint) else "not mounted")
    elif choice == "2":
        try:
            gdrv.mount(cfg.get('gdrive_remote'), mountpoint)
            print("Mounting... Please wait a few seconds and check again.")
        except Exception as e:
            print(f"Error mounting: {e}")
    elif choice == "3":
        try:
            local = input("Локальный путь: ")
            remote = input("Облачный (например gdrive:folder): ")
            gdrv.sync(local, remote)
            print("Sync completed.")
        except Exception as e:
            print(f"Error syncing: {e}")


def auto_start_server(cfg):
    """Auto start the last server if enabled."""
    if not cfg.get('auto_start_enabled', False):
        return
    last_server = cfg.get('last_server_path', '')
    last_ram = cfg.get('last_server_ram', '2G')
    if not last_server or not os.path.exists(last_server):
        print("Последний сервер не найден, автозагрузка пропущена")
        return
    print(f"Автозагрузка сервера: {last_server} с RAM: {last_ram}")
    run_server(last_server, last_ram, cfg)


def main():
    cfg = load_cfg()
    
    # Check for auto start
    if cfg.get('auto_start_enabled', False) and cfg.get('last_server_path', ''):
        print("Автозагрузка включена. Сервер запустится через 10 секунд...")
        print("Нажмите любую клавишу для отмены автозагрузки")
        
        def countdown():
            for i in range(10, 0, -1):
                print(f"\rАвтозагрузка через {i} секунд... (нажмите Enter для отмены)", end='', flush=True)
                time.sleep(1)
            print("\rЗапуск сервера...                                    ")
            auto_start_server(cfg)
        
        timer_thread = threading.Thread(target=countdown)
        timer_thread.daemon = True
        timer_thread.start()
        
        try:
            # Wait for user input or timer completion
            user_input = input()
            if user_input.strip():  # If user pressed Enter or typed something
                print("Автозагрузка отменена")
                timer_thread.join(timeout=0)  # Stop the countdown thread
        except EOFError:
            # No input, let the timer complete
            timer_thread.join()
    
    # Main menu loop
    while True:
        print("\nГлавное меню")
        print("1) Создать сервер")
        print("2) Выбрать сервер")
        print("3) Настройки")
        print("4) Google Drive")
        print("5) Выход")
        choice = input("> ")
        if choice == "1":
            create_server(cfg)
        elif choice == "2":
            select_server(cfg)
        elif choice == "3":
            settings(cfg)
        elif choice == "4":
            gdrive_menu(cfg)
        elif choice == "5":
            print("Выход")
            break
        else:
            print("Неверный выбор")
    
    while True:
        print("\nГлавное меню")
        print("1) Создать сервер")
        print("2) Выбрать сервер")
        print("3) Настройки")
        print("4) Google Drive")
        print("5) Выход")
        choice = input("> ")
        if choice == "1":
            create_server(cfg)
        elif choice == "2":
            select_server(cfg)
        elif choice == "3":
            settings(cfg)
        elif choice == "4":
            gdrive_menu(cfg)
        elif choice == "5":
            print("Выход")
            break
        else:
            print("Неверный выбор")


if __name__ == "__main__":
    main()
